/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function listDevices(): string;
export declare function setBrightness(deviceName: string, percentage: number): void;
export declare function getBrightness(deviceName: string): number;
