/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require("path");
const { environment } = require("@raycast/api");

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== "function") {
    try {
      const lddPath = require("child_process").execSync("which ldd").toString().trim();
      return readFileSync(lddPath, "utf8").includes("musl");
    } catch (e) {
      return true;
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header;
    return !glibcVersionRuntime;
  }
}

switch (platform) {
  case "win32":
    switch (arch) {
      case "x64":
        localFileExisted = existsSync(join(environment.assetsPath, "bin/mixer-node.win32-x64-msvc.node"));
        try {
          if (localFileExisted) {
            nativeBinding = require(join(environment.assetsPath, "bin/mixer-node.win32-x64-msvc.node"));
          } else {
            nativeBinding = require("mixer-node-win32-x64-msvc");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error(`Failed to load native binding`);
}

const { listAudioSessions, setMasterVolume, muteMasterVolume, setAppVolume, setAppMute } = nativeBinding;

module.exports.listAudioSessions = listAudioSessions;
module.exports.setMasterVolume = setMasterVolume;
module.exports.muteMasterVolume = muteMasterVolume;
module.exports.setAppVolume = setAppVolume;
module.exports.setAppMute = setAppMute;
