/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function listAudioSessions(): string
export declare function setMasterVolume(volume: number): string
export declare function muteMasterVolume(mute: boolean): string
export declare function setAppVolume(pid: number, volume: number): string
export declare function setAppMute(pid: number, mute: boolean): string
