/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Toggle Windows light/dark theme */
export declare function themeToggle(): string
/** Get current Windows theme */
export declare function getTheme(): string
